version: '3'
services:
  face_api:
    image: talgin/face_api_image:v1.1
    container_name: face_api
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/talgat/PROJECTS/INFERENCE/crops:/crops
    working_dir: /face_api
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:9999 --forwarded-allow-ips "*" --workers 6 --log-level debug
